//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MROCoatching.DataObjects.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MROCoatching.DataObjects.Shared.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while creating new the record.
        /// </summary>
        internal static string ErrorOccuredWhileCreatingRecord {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileCreatingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while deleting the record.
        /// </summary>
        internal static string ErrorOccuredWhileDeletingRecord {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileDeletingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while updating the record.
        /// </summary>
        internal static string ErrorOccuredWhileUpdatingRecord {
            get {
                return ResourceManager.GetString("ErrorOccuredWhileUpdatingRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation  not successful.
        /// </summary>
        internal static string OperationWasNotSucessful {
            get {
                return ResourceManager.GetString("OperationWasNotSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists.
        /// </summary>
        internal static string RecordAlreadyExist {
            get {
                return ResourceManager.GetString("RecordAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sucessfully created.
        /// </summary>
        internal static string RecordSucessfullyCreated {
            get {
                return ResourceManager.GetString("RecordSucessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sucessfully deleted.
        /// </summary>
        internal static string RecordSucessfullyDeleted {
            get {
                return ResourceManager.GetString("RecordSucessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record sucessfully updated.
        /// </summary>
        internal static string RecordSucessfullyUpdated {
            get {
                return ResourceManager.GetString("RecordSucessfullyUpdated", resourceCulture);
            }
        }

        ///<summary>
        ///looks up a localized string similar to Record sucessfully Approved.
        ///</summary>
        internal static string RecordSucessfullyApproved
        {
            get
            {
                return ResourceManager.GetString("ActionwasRejected", resourceCulture);
            }
        }
        ///<summary>
        ///looks up a localized string similar to Action sucessfully Rejected.
        ///</summary>
        internal static string ActionwasRejected
        {
            get
            {
                return ResourceManager.GetString("ActionwasRejected", resourceCulture);
            }
        }
    }
}
